name: Update GUI Screenshot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb x11-apps imagemagick

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Build the project
        run: cargo build --release

      - name: Run the application inside Xvfb
        run: |
          Xvfb :99 -screen 0 1024x768x24 &
          export DISPLAY=:99
          ./target/release/pota-browser &
          sleep 5
          import -window root screenshot.png
          pkill -f pota-browser

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update GUI screenshot"
          file_pattern: screenshot.png
