name: Capture GUI Screenshot

on:
  push:
    branches:
      - main
  workflow_dispatch:  # lancio manuale

jobs:
  capture-screenshot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb imagemagick libgtk-3-dev libx11-dev libgl1-mesa-glx

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Build project
      run: cargo build --release

    - name: Run with virtual display and capture screenshot
      run: |
        # Avvia Xvfb
        Xvfb :99 -screen 0 1280x720x24 &
        export DISPLAY=:99

        # Avvia pota-browser in background
        ./target/release/pota-browser &
        sleep 5  # Aspetta qualche secondo che si apra

        # Cattura screenshot della finestra attiva
        import -window root screenshot.png || \
        (echo "Failed to capture screenshot, falling back to full screen" && import -window root screenshot.png)

    - name: Upload Screenshot Artifact
      uses: actions/upload-artifact@v4
      with:
        name: gui-screenshot
        path: screenshot.png

    - name: Commit and Push Screenshot (optional)
      run: |
        mv screenshot.png assets/pota-browser-screenshot.png
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add assets/pota-browser-screenshot.png
        git commit -m "Update GUI screenshot"
        git push
