name: Capture GUI Screenshot

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  capture-screenshot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Debug Current Directory
      run: |
        echo "Current directory is:"
        pwd
        echo "Listing files:"
        ls -lah

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          xvfb \
          imagemagick \
          libgtk-3-dev \
          libx11-dev \
          libgl1 \
          libegl1 \
          libglib2.0-dev \
          libgdk-pixbuf2.0-0

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Build project
      run: cargo build --release
      working-directory: ${{ github.workspace }}

    - name: Debug Build Output
      run: |
        echo "Listing target/release:"
        ls -lah target/release
      working-directory: ${{ github.workspace }}

    - name: Run with virtual display and capture screenshot
      run: |
        Xvfb :99 -screen 0 1280x720x24 &
        export DISPLAY=:99
        "${{ github.workspace }}/target/release/pota-browser" &
        sleep 5
        import -window root screenshot.png || \
        (echo "⚠️ Failed to capture window, falling back to full screen." && import -window root screenshot.png)
      working-directory: ${{ github.workspace }}

    - name: Upload Screenshot Artifact
      uses: actions/upload-artifact@v4
      with:
        name: gui-screenshot
        path: screenshot.png

    - name: Commit and Push Screenshot
      run: |
        mkdir -p assets
        mv screenshot.png assets/pota-browser-screenshot.png
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add assets/pota-browser-screenshot.png
        git commit -m "Update GUI screenshot"
        git push
      working-directory: ${{ github.workspace }}
